
export const alertConstants = {
  SET_ALERT: 'SET_ALERT_TEST',
  REMOVE_ALERT: 'REMOVE_ALERT_TEST'
}

export const usersConstants = {
  USER_LOADED: 'USER_LOADED'
}

export const postsConstants = {
  POSTS_REQUEST: 'POSTS_REQUEST',

  GET_POSTS: 'GET_POSTS',
  GET_POST: 'GET_POST',
  GET_MY_POSTS: 'GET_MY_POSTS',

  FILTER_POSTS: 'FILTER_POSTS',

  ADD_POST: 'ADD_POST',
  ADD_COMMENT: 'ADD_COMMENT',

  REMOVE_COMMENT: 'REMOVE_COMMENT',
  UPDATE_LIKES: 'UPDATE_LIKES',
  DELETE_POST: 'DELETE_POST',
  POST_ERROR: 'POST_ERROR'
}

export const profileConstants = {
  PROFILE_REQUEST: 'PROFILE_REQUEST',
  GET_PROFILE: 'GET_PROFILE',
  CLEAR_PROFILE: 'CLEAR_PROFILE',
  PROFILE_ERROR: 'PROFILE_ERROR'
}

export const authConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT'
}
